# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 14:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('postulante', '0003_auto_20170819_2259'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=200)),
                ('municipio', models.CharField(max_length=200)),
                ('parroquia', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ExperienciaLaboral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tempresa', models.CharField(max_length=200)),
                ('cargo', models.CharField(max_length=200)),
                ('vempresa', models.CharField(max_length=200)),
                ('anos', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='postulante',
            name='domicilio',
        ),
        migrations.AddField(
            model_name='experiencialaboral',
            name='postulante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='postulante.Postulante'),
        ),
        migrations.AddField(
            model_name='direccion',
            name='postulante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='postulante.Postulante'),
        ),
    ]
