# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 00:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('postulante', '0006_auto_20170904_2000'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargopostualado', models.CharField(max_length=200)),
                ('postulante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='postulante.Postulante')),
            ],
        ),
    ]
