# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postulante', '0008_auto_20170908_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='examen',
            name='realizado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
