# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-20 14:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postulante', '0010_auto_20170920_1340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experiencialaboral',
            old_name='cargo',
            new_name='cargov',
        ),
    ]
