# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-20 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postulante', '0011_auto_20170920_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examen',
            name='cargo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
