# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-20 15:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('postulante', '0012_auto_20170920_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examen',
            name='cargo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='postulante.Cargo'),
        ),
    ]
