# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-21 03:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postulante', '0013_auto_20170920_1522'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Preguntas',
            new_name='Pregunta',
        ),
    ]
