# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-21 03:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postulante', '0014_auto_20170921_0320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='p1',
            field=models.CharField(default='n/a', max_length=200),
        ),
    ]
