# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-02 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postulante', '0016_respuesta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='p1',
            field=models.CharField(max_length=200),
        ),
    ]
