# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-03 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postulante', '0017_auto_20171002_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examen',
            name='p1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
