# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-09 00:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('postulante', '0019_cargo_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='RespuestaCo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r1', models.CharField(blank=True, max_length=200, null=True)),
                ('r2', models.CharField(blank=True, max_length=200, null=True)),
                ('r3', models.CharField(blank=True, max_length=200, null=True)),
                ('r4', models.CharField(blank=True, max_length=200, null=True)),
                ('r5', models.CharField(blank=True, max_length=200, null=True)),
                ('r6', models.CharField(blank=True, max_length=200, null=True)),
                ('r7', models.CharField(blank=True, max_length=200, null=True)),
                ('r8', models.CharField(blank=True, max_length=200, null=True)),
                ('r9', models.CharField(blank=True, max_length=200, null=True)),
                ('r10', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='respuesta',
            name='pregunta',
        ),
        migrations.AddField(
            model_name='respuesta',
            name='cargo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='postulante.Cargo'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AddField(
            model_name='respuestaco',
            name='cargo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='postulante.Cargo'),
        ),
    ]
